# Generated by Django 5.2.16 on 2026-07-24 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socialaccount', '0006_alter_socialaccount_extra_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'X/Twitter'), ('linkedin', 'LinkedIn'), ('pinterest', 'Pinterest')], max_length=20)),
                ('display_name', models.CharField(max_length=255)),
                ('platform_account_id', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('social_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connected_profile', to='socialaccount.socialaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['platform', 'display_name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'platform', 'platform_account_id'), name='unique_connected_profile_per_platform_account')],
            },
        ),
    ]
