# Generated by Django 5.2.16 on 2026-07-24 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('socialaccount', '0006_alter_socialaccount_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedprofile',
            name='page_access_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='connectedprofile',
            name='social_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_profiles', to='socialaccount.socialaccount'),
        ),
    ]
