# Generated by Django 5.2.16 on 2026-07-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_connectedprofile_page_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedprofile',
            name='token_obtained_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
