# Generated by Django 5.2.16 on 2026-07-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_pending_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(choices=[('Asia/Dhaka', 'Asia/Dhaka'), ('UTC', 'UTC'), ('America/New_York', 'America/New_York'), ('America/Chicago', 'America/Chicago'), ('America/Denver', 'America/Denver'), ('America/Los_Angeles', 'America/Los_Angeles'), ('America/Toronto', 'America/Toronto'), ('America/Sao_Paulo', 'America/Sao_Paulo'), ('Europe/London', 'Europe/London'), ('Europe/Paris', 'Europe/Paris'), ('Europe/Berlin', 'Europe/Berlin'), ('Africa/Cairo', 'Africa/Cairo'), ('Africa/Johannesburg', 'Africa/Johannesburg'), ('Asia/Dubai', 'Asia/Dubai'), ('Asia/Kolkata', 'Asia/Kolkata'), ('Asia/Singapore', 'Asia/Singapore'), ('Asia/Tokyo', 'Asia/Tokyo'), ('Australia/Sydney', 'Australia/Sydney'), ('Pacific/Auckland', 'Pacific/Auckland')], default='Asia/Dhaka', max_length=64),
        ),
    ]
