# Generated by Django 5.2.16 on 2026-07-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_create_check_scheduled_posts_periodic_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='posttarget',
            name='board_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='posttarget',
            name='board_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
